// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"github.com/ujunglangit-id/sqlc/internal/sql/ast"
	"github.com/ujunglangit-id/sqlc/internal/sql/catalog"
)

func Tcn() *catalog.Schema {
	s := &catalog.Schema{Name: "pg_catalog"}
	s.Funcs = []*catalog.Function{
		{
			Name:       "triggered_change_notification",
			Args:       []*catalog.Argument{},
			ReturnType: &ast.TypeName{Name: "trigger"},
		},
	}
	return s
}
